[ADD] categories View
Platzi-Master-C8/gethired-community pull request #2
Opened 2022-01-18 04:51 UTC by carlosmen351

## Checklist ✅

- [ ] I have followed the [contributor guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md)
- [ ] Tests are included
- [ ] Documentation is changed or added
- [ ] Related issue has been created
- [ ] Commits messages follows [commit guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md/#Commits)

resolves [Issue ID]

2022-01-18 04:53 UTC, carlosmen351 commented
Creando la vista de categorias

2022-01-19 19:08 UTC, dannzdev requested changes
Hi Carlos I like your styles bu there is a few changes that you could made in order have a cleaner code of your updates:

1- Try to improve your naming, we need names that specify the component. Try to avoid Boton1-Boton2, Cajacopia2 instead of that : try to use a more specific name like. DangerBotton or ChallengeBox, etc.
2- We are using PascalCase, be careful with naming. You named ImgTarjeta(English with Spanish wrong, but good PascalCase) and here( Cajacopia2 is not PascalCase and is all in Spanish)
3- Try to use English. We cannot lose time changing names of every style from spanish to english. If everything is english keep it that way. The content is the only thing in Spanish.

I think with that modified we can continue with merging!

2022-01-20 16:26 UTC, geekdann approved these changes

2022-01-21 00:39 UTC, andresalvarezb approved these changes

2022-01-21 00:39 UTC, merged